name: Update Terraform Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: write-all


jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Update Terraform Docs
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: ./IaC
          
      - name: Commit changes to the repository
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Commiting Updates to Terraform Documentation. 
